/**
 * Serverless Function: Claude-Powered Website Audit
 *
 * Flow:
 *   1. Receives { contactId?, firstName, lastName?, email, phone?, website } via POST
 *   2. If no contactId, creates a CRM contact
 *   3. Attempts Google PageSpeed Insights API (optional)
 *   4. Sends data to Claude — always proceeds even if PageSpeed fails
 *   5. Posts Claude's report as a note on the CRM contact
 *   6. Applies the "audit-complete" tag to the contact
 *   7. Returns 200 success
 *
 * === ENVIRONMENT VARIABLES (set on Vercel) ===
 *   ANTHROPIC_API_KEY = sk-ant-...  (from https://console.anthropic.com)
 *   CRM_API_KEY       = pit-...     (from your CRM: Settings -> API -> API Key)
 */

export const config = { maxDuration: 60 };

interface AuditRequest {
  contactId?: string;
  firstName: string;
  lastName?: string;
  email: string;
  phone?: string;
  website: string;
}

async function fetchWithTimeout(url: string, options: RequestInit = {}, timeoutMs = 15000): Promise<Response> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { ...options, signal: controller.signal });
    clearTimeout(timeoutId);
    return res;
  } catch (err) {
    clearTimeout(timeoutId);
    throw err;
  }
}

async function fetchPageSpeedData(target: string): Promise<any | null> {
  const psiUrl = `https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=${encodeURIComponent(target)}&strategy=mobile&category=PERFORMANCE&category=SEO&category=BEST_PRACTICES&category=ACCESSIBILITY`;
  try {
    const res = await fetchWithTimeout(psiUrl, {}, 15000);
    const data = await res.json();
    if (data?.lighthouseResult && !data?.error) return data.lighthouseResult;
  } catch {}
  return null;
}

const AUDIT_SYSTEM_PROMPT = `You are a senior SEO and web performance consultant performing a professional website audit for a potential client. You will receive whatever data is available — which may include Google PageSpeed Insights scores or just the URL. Work with whatever you have.

Include:
1. Executive Summary — 2-3 sentences on overall health and biggest opportunities.
2. Performance Scores — speed, SEO, best practices, accessibility (0-100). Use PageSpeed data if available; use general knowledge if only URL available.
3. Key Issues — 5-10 issues ordered by severity (high/medium/low).
4. Recommendations — 5-8 concrete, actionable items.
5. Conversion Opportunities — where the site could better capture leads or book appointments.

Rules: never refuse due to limited data. Be honest and specific. Write for a non-technical business owner. Use clean markdown.`;

async function callClaude(target: string, pageSpeed: any | null): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY not set');

  const lhScores = pageSpeed
    ? `PageSpeed Scores:
- Performance: ${Math.round((pageSpeed.categories?.performance?.score ?? 0) * 100)}/100
- SEO: ${Math.round((pageSpeed.categories?.seo?.score ?? 0) * 100)}/100
- Best Practices: ${Math.round((pageSpeed.categories?.['best-practices']?.score ?? 0) * 100)}/100
- Accessibility: ${Math.round((pageSpeed.categories?.accessibility?.score ?? 0) * 100)}/100

Key Audits:
${Object.entries(pageSpeed.audits || {})
  .filter(([, a]: any) => a.score !== null && a.score < 0.9 && a.title)
  .slice(0, 15)
  .map(([, a]: any) => `- ${a.title}: ${Math.round((a.score ?? 0) * 100)}/100${a.numericValue ? ` (${a.displayValue || a.numericValue})` : ''}`)
  .join('\n')}`
    : 'PageSpeed data unavailable. Audit based on URL and general best practices.';

  const userMessage = `Audit this website: ${target}\n\n${lhScores}\n\nProvide the full report now.`;

  const response = await fetchWithTimeout('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1500,
      system: AUDIT_SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userMessage }],
    }),
  }, 20000);

  if (!response.ok) throw new Error(`Claude error ${response.status}: ${await response.text()}`);
  const data = await response.json();
  const text = data?.content?.[0]?.text;
  if (!text) throw new Error('Empty response from Claude');
  return text;
}

const CRM_BASE = 'https://services.leadconnectorhq.com';

async function addNoteToContact(contactId: string, report: string, firstName: string, website: string): Promise<void> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const body = `AI Website Audit — ${website}\n\n${report}\n\n---\nGenerated by Framework Digital AI audit system for ${firstName}.`;
  const res = await fetchWithTimeout(`${CRM_BASE}/contacts/${contactId}/notes`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({ body }),
  }, 15000);
  if (!res.ok) throw new Error(`Note failed ${res.status}: ${await res.text()}`);
}

async function addTagToContact(contactId: string, tag: string): Promise<void> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const res = await fetchWithTimeout(`${CRM_BASE}/contacts/${contactId}/tags`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({ tags: [tag] }),
  }, 15000);
  if (!res.ok) throw new Error(`Tag failed ${res.status}: ${await res.text()}`);
}

async function createContact(data: { firstName: string; lastName?: string; email: string; phone?: string; website: string }): Promise<string> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const res = await fetchWithTimeout(`${CRM_BASE}/contacts/`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({
      firstName: data.firstName,
      lastName: data.lastName || '',
      email: data.email,
      phone: data.phone || '',
      website: data.website,
      locationId: 'OUrWlaebgMJpay1aHLiC',
    }),
  }, 15000);
  if (!res.ok) throw new Error(`Contact creation failed ${res.status}: ${await res.text()}`);
  const result = await res.json();
  const id = result?.contact?.id || result?.id;
  if (!id) throw new Error('No contactId returned');
  return id;
}

export default async function handler(req: Request): Promise<Response> {
  const headers: Record<string, string> = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json',
  };

  if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers });
  if (req.method !== 'POST') return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405, headers });

  try {
    let body: AuditRequest;
    try { body = JSON.parse(await req.text()); }
    catch { return new Response(JSON.stringify({ error: 'Invalid JSON' }), { status: 400, headers }); }

    const { contactId: passedId, firstName, lastName, email, phone, website } = body;
    if (!website || !email) return new Response(JSON.stringify({ error: 'email and website required' }), { status: 400, headers });

    let contactId = passedId;
    if (!contactId) {
      console.log(`[Audit] Creating contact for ${email}`);
      contactId = await createContact({ firstName, lastName, email, phone, website });
    }

    let target = website.trim();
    if (!/^https?:\/\//i.test(target)) target = 'https://' + target;

    console.log(`[Audit] Starting for ${target}`);
    const pageSpeed = await fetchPageSpeedData(target);
    console.log(`[Audit] PageSpeed: ${pageSpeed ? 'yes' : 'no'}`);

    const report = await callClaude(target, pageSpeed);
    console.log(`[Audit] Claude done (${report.length} chars)`);

    await addNoteToContact(contactId, report, firstName, target);
    await addTagToContact(contactId, 'audit-complete');
    console.log('[Audit] Done.');

    return new Response(JSON.stringify({ success: true, contactId, website: target }), { status: 200, headers });

  } catch (error: any) {
    console.error('[Audit]', error.message);
    return new Response(JSON.stringify({ success: false, error: error.message }), { status: 500, headers });
  }
}

    
This version: no HTML proxies at all, PageSpeed timeout reduced to 15s, Claude at 1500 tokens with 20s timeout. Total worst case: ~35s, well within Vercel's 60s. Paste, commit, tell me when it's Ready.

done


Thinking
Thought process
Commit live. Firing test — with no HTML proxies this should finish in under 20s:

Checking for a note — it may have completed after my timeout:

The deployment may not have finished yet — that's likely still the old version running. Can you check vercel.com/framework-digital/audit-function/deployments and confirm the newest deployment shows Ready before I fire the test?

ready


Thinking
Thought process
Still timing out. Even without HTML proxies. At this point it's either PageSpeed hanging OR a proxy connection issue between my tool and Vercel. Let me strip it down to absolutely nothing except Claude and the CRM — no external fetching at all:

api/audit.ts — diagnostic version (no PageSpeed)
      
/**
 * Serverless Function: Claude-Powered Website Audit
 * CRM_API_KEY = pit-... (Vercel env var)
 * ANTHROPIC_API_KEY = sk-ant-... (Vercel env var)
 */

export const config = { maxDuration: 60 };

interface AuditRequest {
  contactId?: string;
  firstName: string;
  lastName?: string;
  email: string;
  phone?: string;
  website: string;
}

async function callClaude(target: string): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY not set');

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1500,
      system: 'You are a senior SEO and web performance consultant. Audit the given website URL using your general knowledge. Include: Executive Summary, Performance Scores (estimated), Key Issues, Recommendations, Conversion Opportunities. Be specific and honest. Use clean markdown.',
      messages: [{ role: 'user', content: `Perform a full website audit for: ${target}` }],
    }),
  });

  if (!response.ok) throw new Error(`Claude error ${response.status}: ${await response.text()}`);
  const data = await response.json();
  const text = data?.content?.[0]?.text;
  if (!text) throw new Error('Empty response from Claude');
  return text;
}

const CRM_BASE = 'https://services.leadconnectorhq.com';

async function addNoteToContact(contactId: string, report: string, firstName: string, website: string): Promise<void> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const res = await fetch(`${CRM_BASE}/contacts/${contactId}/notes`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({ body: `AI Website Audit — ${website}\n\n${report}\n\n---\nGenerated by Framework Digital AI audit system for ${firstName}.` }),
  });
  if (!res.ok) throw new Error(`Note failed ${res.status}: ${await res.text()}`);
}

async function addTagToContact(contactId: string, tag: string): Promise<void> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const res = await fetch(`${CRM_BASE}/contacts/${contactId}/tags`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({ tags: [tag] }),
  });
  if (!res.ok) throw new Error(`Tag failed ${res.status}: ${await res.text()}`);
}

async function createContact(data: { firstName: string; lastName?: string; email: string; phone?: string; website: string }): Promise<string> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const res = await fetch(`${CRM_BASE}/contacts/`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({
      firstName: data.firstName,
      lastName: data.lastName || '',
      email: data.email,
      phone: data.phone || '',
      website: data.website,
      locationId: 'OUrWlaebgMJpay1aHLiC',
    }),
  });
  if (!res.ok) throw new Error(`Contact creation failed ${res.status}: ${await res.text()}`);
  const result = await res.json();
  const id = result?.contact?.id || result?.id;
  if (!id) throw new Error('No contactId returned');
  return id;
}

export default async function handler(req: Request): Promise<Response> {
  const headers: Record<string, string> = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json',
  };

  if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers });
  if (req.method !== 'POST') return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405, headers });

  try {
    let body: AuditRequest;
    try { body = JSON.parse(await req.text()); }
    catch { return new Response(JSON.stringify({ error: 'Invalid JSON' }), { status: 400, headers }); }

    const { contactId: passedId, firstName, lastName, email, phone, website } = body;
    if (!website || !email) return new Response(JSON.stringify({ error: 'email and website required' }), { status: 400, headers });

    let contactId = passedId;
    if (!contactId) {
      contactId = await createContact({ firstName, lastName, email, phone, website });
    }

    let target = website.trim();
    if (!/^https?:\/\//i.test(target)) target = 'https://' + target;

    console.log(`[Audit] Starting Claude for ${target}`);
    const report = await callClaude(target);
    console.log(`[Audit] Claude done (${report.length} chars)`);

    await addNoteToContact(contactId, report, firstName, target);
    await addTagToContact(contactId, 'audit-complete');
    console.log('[Audit] Done.');

    return new Response(JSON.stringify({ success: true, contactId, website: target }), { status: 200, headers });

  } catch (error: any) {
    console.error('[Audit]', error.message);
    return new Response(JSON.stringify({ success: false, error: error.message }), { status: 500, headers });
  }
}
