/**
 * Serverless Function: Claude-Powered Website Audit
 * ANTHROPIC_API_KEY = sk-ant-... (Vercel env var)
 * CRM_API_KEY       = pit-...    (Vercel env var)
 */

export const config = { maxDuration: 60 };

interface AuditRequest {
  contactId?: string;
  firstName: string;
  lastName?: string;
  email: string;
  phone?: string;
  website: string;
}

async function callClaude(target: string): Promise<{ summaryHtml: string; fullReport: string }> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY not set');

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 45000);

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-opus-4-5',
        max_tokens: 1800,
        system: `You are a senior SEO and web performance consultant auditing a website for a potential client.

Return your response in EXACTLY this format:

===EMAIL_SUMMARY===
Write 4-5 findings as HTML using ONLY <ul> and <li> tags. Each <li> should start with the finding name followed by a colon, then one specific recommendation. No bold, no extra HTML tags, no styling attributes. Friendly tone, written for a business owner.

===FULL_REPORT===
Start with this grades table in markdown (fill in real letter grades A/B/C/D/F and scores):

## Site Grades

| Category | Grade | Score |
|----------|-------|-------|
| Page Speed & Performance | ? | ?/100 |
| SEO & Search Visibility | ? | ?/100 |
| Mobile Experience | ? | ?/100 |
| Content Quality | ? | ?/100 |
| User Experience & Conversion | ? | ?/100 |
| Technical & Security | ? | ?/100 |
| **Overall** | **?** | **?/100** |

Then include:

## Executive Summary
3-4 sentences covering overall health, biggest strengths, and most critical opportunities.

## Key Issues
6-10 specific issues ordered by severity. Label each HIGH / MEDIUM / LOW.

## Recommendations
6-8 concrete, actionable items with clear steps a business owner can understand.

## Quick Wins
3-4 things they can fix this week for immediate improvement.

## Conversion Opportunities
Where the site is losing potential leads or sales and exactly how to fix it.`,
        messages: [{ role: 'user', content: `Audit this website: ${target}` }],
      }),
      signal: controller.signal,
    });
    clearTimeout(timeout);

    if (!response.ok) throw new Error(`Claude error ${response.status}: ${await response.text()}`);
    const data = await response.json();
    const raw: string = data?.content?.[0]?.text;
    if (!raw) throw new Error('Empty response from Claude');

    const summaryMatch = raw.match(/===EMAIL_SUMMARY===([\s\S]*?)===FULL_REPORT===/);
    const fullMatch = raw.match(/===FULL_REPORT===([\s\S]*)/);

    const summaryHtml = summaryMatch?.[1]?.trim() ?? '<ul><li>Audit complete — see your full report via the link below.</li></ul>';
    const fullReport = fullMatch?.[1]?.trim() ?? raw;

    return { summaryHtml, fullReport };
  } catch (err: any) {
    clearTimeout(timeout);
    if (err.name === 'AbortError') throw new Error('Claude timed out after 45s');
    throw err;
  }
}

const CRM_BASE = 'https://services.leadconnectorhq.com';
const AUDIT_SUMMARY_FIELD_ID = 'BWWIBWHOzsF67mN1IjJJ';

async function addNoteToContact(contactId: string, report: string, firstName: string, website: string): Promise<void> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const res = await fetch(`${CRM_BASE}/contacts/${contactId}/notes`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({ body: `AI Website Audit — ${website}\n\n${report}\n\n---\nGenerated by Framework Digital AI audit system for ${firstName}.` }),
  });
  if (!res.ok) throw new Error(`Note failed ${res.status}: ${await res.text()}`);
}

async function updateContactSummaryField(contactId: string, summaryHtml: string): Promise<void> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const res = await fetch(`${CRM_BASE}/contacts/${contactId}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({ customFields: [{ id: AUDIT_SUMMARY_FIELD_ID, value: summaryHtml }] }),
  });
  if (!res.ok) throw new Error(`Custom field update failed ${res.status}: ${await res.text()}`);
}

async function addTagToContact(contactId: string, tag: string): Promise<void> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const res = await fetch(`${CRM_BASE}/contacts/${contactId}/tags`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({ tags: [tag] }),
  });
  if (!res.ok) throw new Error(`Tag failed ${res.status}: ${await res.text()}`);
}

async function createContact(data: { firstName: string; lastName?: string; email: string; phone?: string; website: string }): Promise<string> {
  const key = process.env.CRM_API_KEY;
  if (!key) throw new Error('CRM_API_KEY not set');
  const res = await fetch(`${CRM_BASE}/contacts/`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
    body: JSON.stringify({
      firstName: data.firstName,
      lastName: data.lastName || '',
      email: data.email,
      phone: data.phone || '',
      website: data.website,
      locationId: 'OUrWlaebgMJpay1aHLiC',
    }),
  });
  if (!res.ok) throw new Error(`Contact creation failed ${res.status}: ${await res.text()}`);
  const result = await res.json();
  const id = result?.contact?.id || result?.id;
  if (!id) throw new Error('No contactId returned');
  return id;
}

const corsHeaders: Record<string, string> = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Content-Type': 'application/json',
};

export async function OPTIONS(): Promise<Response> {
  return new Response(null, { status: 204, headers: corsHeaders });
}

export async function POST(req: Request): Promise<Response> {
  try {
    let body: AuditRequest;
    try { body = JSON.parse(await req.text()); }
    catch { return new Response(JSON.stringify({ error: 'Invalid JSON' }), { status: 400, headers: corsHeaders }); }

    const { contactId: passedId, firstName, lastName, email, phone, website } = body;
    if (!website || !email) return new Response(JSON.stringify({ error: 'email and website required' }), { status: 400, headers: corsHeaders });

    let contactId = passedId;
    if (!contactId) {
      contactId = await createContact({ firstName, lastName, email, phone, website });
    }

    let target = website.trim();
    if (!/^https?:\/\//i.test(target)) target = 'https://' + target;

    console.log(`[Audit] Calling Claude for ${target}`);
    const { summaryHtml, fullReport } = await callClaude(target);
    console.log(`[Audit] Claude done — summary: ${summaryHtml.length} chars, report: ${fullReport.length} chars`);

    await addNoteToContact(contactId, fullReport, firstName, target);
    await updateContactSummaryField(contactId, summaryHtml);
    await addTagToContact(contactId, 'audit-complete');
    console.log('[Audit] Complete.');

    return new Response(JSON.stringify({ success: true, contactId, website: target }), { status: 200, headers: corsHeaders });

  } catch (error: any) {
    console.error('[Audit] ERROR:', error.message);
    return new Response(JSON.stringify({ success: false, error: error.message }), { status: 500, headers: corsHeaders });
  }
}
