/**
 * Report viewer — renders a contact's audit note as a branded HTML page
 * GET /api/report?id=CONTACT_ID
 */

const CRM_BASE = 'https://services.leadconnectorhq.com';
const BOOKING_LINK = 'https://api.leadconnectorhq.com/widget/booking/bookwithuswebdesign-fb89806c-32ca-4c6c-adb0-2b1e3b824fe3';

export async function GET(req: Request): Promise<Response> {
  const url = new URL(req.url);
  const contactId = url.searchParams.get('id');

  if (!contactId) {
    return new Response('Missing report ID.', { status: 400, headers: { 'Content-Type': 'text/plain' } });
  }

  const key = process.env.CRM_API_KEY;
  if (!key) return new Response('Server error.', { status: 500 });

  const notesRes = await fetch(`${CRM_BASE}/contacts/${contactId}/notes`, {
    headers: { 'Authorization': `Bearer ${key}`, 'Version': '2021-07-28' },
  });

  if (!notesRes.ok) {
    return new Response('Report not found.', { status: 404, headers: { 'Content-Type': 'text/plain' } });
  }

  const notesData = await notesRes.json();
  const notes: any[] = notesData.notes || [];
  const auditNote = notes.find((n: any) => n.body?.startsWith('AI Website Audit'));

  if (!auditNote) {
    return new Response('No audit report found for this contact.', { status: 404, headers: { 'Content-Type': 'text/plain' } });
  }

  const websiteMatch = auditNote.body.match(/AI Website Audit — (https?:\/\/[^\n]+)/);
  const website = websiteMatch?.[1]?.trim() || 'your website';

  const reportMarkdown = auditNote.body
    .replace(/^AI Website Audit — [^\n]+\n\n/, '')
    .replace(/\n\n---\nGenerated by Framework Digital[\s\S]*$/, '')
    .trim();

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Website Audit Report — ${website}</title>
  <script src="https://cdn.jsdelivr.net/npm/marked@9/marked.min.js"></script>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.7; }
    .header { background: #0f172a; color: white; padding: 40px 24px; text-align: center; }
    .header .logo { font-size: 14px; letter-spacing: 2px; text-transform: uppercase; color: #64748b; margin-bottom: 12px; }
    .header h1 { font-size: 28px; font-weight: 700; margin-bottom: 8px; }
    .header p { color: #94a3b8; font-size: 15px; }
    .cta-top { background: #2563eb; padding: 18px 24px; text-align: center; }
    .cta-top a { display: inline-block; background: white; color: #2563eb; padding: 11px 28px; border-radius: 6px; font-weight: 700; text-decoration: none; font-size: 15px; }
    .container { max-width: 820px; margin: 0 auto; padding: 40px 24px; }
    .report h2 { font-size: 22px; font-weight: 700; color: #0f172a; margin: 36px 0 14px; padding-bottom: 8px; border-bottom: 2px solid #e2e8f0; }
    .report h3 { font-size: 17px; font-weight: 600; color: #1e40af; margin: 24px 0 8px; }
    .report p { margin-bottom: 16px; font-size: 15px; }
    .report ul, .report ol { margin: 10px 0 18px 22px; }
    .report li { margin-bottom: 10px; font-size: 15px; }
    .report table { width: 100%; border-collapse: collapse; margin: 8px 0 28px; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
    .report thead th { background: #1e40af; color: white; padding: 13px 18px; text-align: left; font-size: 14px; font-weight: 600; }
    .report tbody td { padding: 12px 18px; border-bottom: 1px solid #f1f5f9; font-size: 14px; }
    .report tbody tr:last-child td { border-bottom: none; }
    .report tbody tr:last-child { font-weight: 700; background: #f8fafc; }
    .report strong { color: #0f172a; }
    .footer-cta { background: white; border: 2px solid #e2e8f0; border-radius: 12px; padding: 36px; text-align: center; margin-top: 48px; }
    .footer-cta h3 { font-size: 22px; font-weight: 700; margin-bottom: 12px; color: #0f172a; }
    .footer-cta p { color: #64748b; margin-bottom: 24px; max-width: 480px; margin-left: auto; margin-right: auto; }
    .footer-cta a { display: inline-block; background: #2563eb; color: white; padding: 15px 36px; border-radius: 8px; font-weight: 700; text-decoration: none; font-size: 16px; }
    .footer-cta a:hover { background: #1d4ed8; }
    .branding { text-align: center; padding: 28px 24px; color: #94a3b8; font-size: 13px; }
    .branding a { color: #2563eb; text-decoration: none; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">Framework Digital</div>
    <h1>Website Audit Report</h1>
    <p>${website}</p>
  </div>
  <div class="cta-top">
    <a href="${BOOKING_LINK}">📅 Book a Free Strategy Call to Discuss Your Results</a>
  </div>
  <div class="container">
    <div id="report" class="report"></div>
    <div class="footer-cta">
      <h3>Ready to fix these issues?</h3>
      <p>Book a free 30-minute strategy call. We'll walk through your results and show you exactly how we'd improve your site — no obligation, no pressure.</p>
      <a href="${BOOKING_LINK}">Book My Free Strategy Call →</a>
    </div>
  </div>
  <div class="branding">
    <p>Report generated by <a href="https://www.frameworkdigitaldesign.com">Framework Digital</a></p>
  </div>
  <script>
    const md = ${JSON.stringify(reportMarkdown)};
    document.getElementById('report').innerHTML = marked.parse(md);
  </script>
</body>
</html>`;

  return new Response(html, {
    status: 200,
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  });
}
